-- Create the admins table with proper constraints and indexes
CREATE TABLE IF NOT EXISTS public.admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  password TEXT NOT NULL,
  name TEXT,
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  last_login TIMESTAMP WITH TIME ZONE,
  CONSTRAINT admins_pkey PRIMARY KEY (id)
);

-- Add a unique index on email if it exists
CREATE UNIQUE INDEX IF NOT EXISTS admins_email_idx ON public.admins(email) 
WHERE email IS NOT NULL;

-- Add default permissions
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

-- Create policies for secure access
CREATE POLICY "Admins can view their own data" 
  ON public.admins FOR SELECT 
  USING (auth.uid()::text = id::text);

CREATE POLICY "Admins can update their own data" 
  ON public.admins FOR UPDATE 
  USING (auth.uid()::text = id::text);

-- Insert a default admin if needed
INSERT INTO public.admins (id, password, name, email)
VALUES (1, 'admin123', 'Default Admin', 'admin@example.com')
ON CONFLICT (id) DO NOTHING;
